project:
  output-dir: build-manuscript

bibliography: bibliography/references.bib
csl: bibliography/styles/chicago-fullnote-bibliography.csl

format:
  docx:
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
    pdf-engine: xelatex
    documentclass: scrbook
    classoption: openany
